"""empty message

Revision ID: 02eb8ec48e69
Revises: 
Create Date: 2023-05-11 13:42:46.064962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02eb8ec48e69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('pub_data', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
